spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost/sell
    username: root
    password: 123456
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  jackson:
    default-property-inclusion: non_null
  redis:
    host: localhost
    port: 6379
server:
  servlet:
    context-path: /sell
wechat:
  mpAppId: wx725796ea31778c76
  mpAppSecret: a15ac79ed233c157322751413b9aeaf0
  orderStatus: Jc8ehn3FJedWWb2qKujnmPH9Dub9ac1mcuQz8xwB4qc
projecturl:
  sell: http://me.cardistry.top
logging:
  level:
    pers.zhw.dataobject.mapper: trace
mybatis:
  mapper-locations: classpath:mapper/*.xml
